import 'package:flutter/material.dart';

abstract class MyThemes {
  static ThemeData theme(ColorScheme colorScheme) {
    return ThemeData(
      useMaterial3: true,
      colorScheme: colorScheme,
    );
  }

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff8d4a5a),
      surfaceTint: Color(0xff8d4a5a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffffd9df),
      onPrimaryContainer: Color(0xff3a0718),
      secondary: Color(0xff75565c),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffffd9df),
      onSecondaryContainer: Color(0xff2b151a),
      tertiary: Color(0xff775a0b),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffdf9e),
      onTertiaryContainer: Color(0xff261a00),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffff8f7),
      onSurface: Color(0xff22191b),
      onSurfaceVariant: Color(0xff524345),
      outline: Color(0xff847375),
      outlineVariant: Color(0xffd6c2c4),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff382e2f),
      inversePrimary: Color(0xffffb1c1),
      primaryFixed: Color(0xffffd9df),
      onPrimaryFixed: Color(0xff3a0718),
      primaryFixedDim: Color(0xffffb1c1),
      onPrimaryFixedVariant: Color(0xff713343),
      secondaryFixed: Color(0xffffd9df),
      onSecondaryFixed: Color(0xff2b151a),
      secondaryFixedDim: Color(0xffe4bdc3),
      onSecondaryFixedVariant: Color(0xff5b3f45),
      tertiaryFixed: Color(0xffffdf9e),
      onTertiaryFixed: Color(0xff261a00),
      tertiaryFixedDim: Color(0xffe9c16c),
      onTertiaryFixedVariant: Color(0xff5b4300),
      surfaceDim: Color(0xffe7d6d8),
      surfaceBright: Color(0xfffff8f7),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff0f1),
      surfaceContainer: Color(0xfffbeaec),
      surfaceContainerHigh: Color(0xfff5e4e6),
      surfaceContainerHighest: Color(0xffefdee0),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff6c2f3f),
      surfaceTint: Color(0xff8d4a5a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffa75f70),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff573b41),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff8d6c72),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff563f00),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff907023),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff8c0009),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffda342e),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f7),
      onSurface: Color(0xff22191b),
      onSurfaceVariant: Color(0xff4d3f42),
      outline: Color(0xff6b5b5e),
      outlineVariant: Color(0xff887679),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff382e2f),
      inversePrimary: Color(0xffffb1c1),
      primaryFixed: Color(0xffa75f70),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff8a4758),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff8d6c72),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff72545a),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff907023),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff755708),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffe7d6d8),
      surfaceBright: Color(0xfffff8f7),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff0f1),
      surfaceContainer: Color(0xfffbeaec),
      surfaceContainerHigh: Color(0xfff5e4e6),
      surfaceContainerHighest: Color(0xffefdee0),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(lightMediumContrastScheme());
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff430e1f),
      surfaceTint: Color(0xff8d4a5a),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff6c2f3f),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff331b21),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff573b41),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff2e2000),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff563f00),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff4e0002),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff8c0009),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f7),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff2d2123),
      outline: Color(0xff4d3f42),
      outlineVariant: Color(0xff4d3f42),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff382e2f),
      inversePrimary: Color(0xffffe6e9),
      primaryFixed: Color(0xff6c2f3f),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff511929),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff573b41),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff3f262b),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff563f00),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff3b2a00),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffe7d6d8),
      surfaceBright: Color(0xfffff8f7),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff0f1),
      surfaceContainer: Color(0xfffbeaec),
      surfaceContainerHigh: Color(0xfff5e4e6),
      surfaceContainerHighest: Color(0xffefdee0),
    );
  }

  ThemeData lightHighContrast() {
    return theme(lightHighContrastScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb1c1),
      surfaceTint: Color(0xffffb1c1),
      onPrimary: Color(0xff551d2d),
      primaryContainer: Color(0xff713343),
      onPrimaryContainer: Color(0xffffd9df),
      secondary: Color(0xffe4bdc3),
      onSecondary: Color(0xff43292f),
      secondaryContainer: Color(0xff5b3f45),
      onSecondaryContainer: Color(0xffffd9df),
      tertiary: Color(0xffe9c16c),
      onTertiary: Color(0xff3f2e00),
      tertiaryContainer: Color(0xff5b4300),
      onTertiaryContainer: Color(0xffffdf9e),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff191113),
      onSurface: Color(0xffefdee0),
      onSurfaceVariant: Color(0xffd6c2c4),
      outline: Color(0xff9e8c8f),
      outlineVariant: Color(0xff524345),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffefdee0),
      inversePrimary: Color(0xff8d4a5a),
      primaryFixed: Color(0xffffd9df),
      onPrimaryFixed: Color(0xff3a0718),
      primaryFixedDim: Color(0xffffb1c1),
      onPrimaryFixedVariant: Color(0xff713343),
      secondaryFixed: Color(0xffffd9df),
      onSecondaryFixed: Color(0xff2b151a),
      secondaryFixedDim: Color(0xffe4bdc3),
      onSecondaryFixedVariant: Color(0xff5b3f45),
      tertiaryFixed: Color(0xffffdf9e),
      onTertiaryFixed: Color(0xff261a00),
      tertiaryFixedDim: Color(0xffe9c16c),
      onTertiaryFixedVariant: Color(0xff5b4300),
      surfaceDim: Color(0xff191113),
      surfaceBright: Color(0xff413738),
      surfaceContainerLowest: Color(0xff140c0e),
      surfaceContainerLow: Color(0xff22191b),
      surfaceContainer: Color(0xff261d1f),
      surfaceContainerHigh: Color(0xff312829),
      surfaceContainerHighest: Color(0xff3c3234),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb8c6),
      surfaceTint: Color(0xffffb1c1),
      onPrimary: Color(0xff330313),
      primaryContainer: Color(0xffc87a8c),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xffe8c1c8),
      onSecondary: Color(0xff251015),
      secondaryContainer: Color(0xffab888e),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffedc670),
      onTertiary: Color(0xff1f1500),
      tertiaryContainer: Color(0xffaf8c3d),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffbab1),
      onError: Color(0xff370001),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff191113),
      onSurface: Color(0xfffff9f9),
      onSurfaceVariant: Color(0xffdac6c8),
      outline: Color(0xffb19ea1),
      outlineVariant: Color(0xff907f81),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffefdee0),
      inversePrimary: Color(0xff723444),
      primaryFixed: Color(0xffffd9df),
      onPrimaryFixed: Color(0xff2c000e),
      primaryFixedDim: Color(0xffffb1c1),
      onPrimaryFixedVariant: Color(0xff5c2232),
      secondaryFixed: Color(0xffffd9df),
      onSecondaryFixed: Color(0xff1f0b10),
      secondaryFixedDim: Color(0xffe4bdc3),
      onSecondaryFixedVariant: Color(0xff492f34),
      tertiaryFixed: Color(0xffffdf9e),
      onTertiaryFixed: Color(0xff191000),
      tertiaryFixedDim: Color(0xffe9c16c),
      onTertiaryFixedVariant: Color(0xff473300),
      surfaceDim: Color(0xff191113),
      surfaceBright: Color(0xff413738),
      surfaceContainerLowest: Color(0xff140c0e),
      surfaceContainerLow: Color(0xff22191b),
      surfaceContainer: Color(0xff261d1f),
      surfaceContainerHigh: Color(0xff312829),
      surfaceContainerHighest: Color(0xff3c3234),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(darkMediumContrastScheme());
  }
}
